### ISSUE TITLE
sourcemap失效

### ISSUE THREAD

**Issue by skyblue** [youzan/fast-uglifyjs-plugin#6]
使用内置uglify plugin是有sourcemap的，
替换后发现失效了。
不知道是否我配置方面有问题？

**Comment by keller35** [comment]
可能是个bug，我看一下。

**Comment by zaaack** [comment]
+1

开启 cache 时 sourcemap 会报这个错 


```
ERROR in vendor.bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack-core/node_modules
/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/optimize/Ug
lifyJsPlugin.js:44:10)
    at Compilation.next (/Users/z/Projects/Douban/share/design/assets/node_modules/tapable/lib/Tapable.js:69:14)
    at Compilation.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/ProgressPlu
gin.js:65:5)
    at Compilation.next (/Users/z/Projects/Douban/share/design/assets/node_modules/tapable/lib/Tapable.js:69:14)
    at Compilation.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/fast-uglifyjs-plugin/li

b/FastUglifyJsPlugin.js:183:17)
    at Compilation.applyPluginsAsync (/Users/z/Projects/Douban/share/design/assets/node_modules/tapable/lib/Tapab
le.js:71:13)
    at Compilation.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/Compilation
.js:567:9)
    at Compilation.applyPluginsAsync (/Users/z/Projects/Douban/share/design/assets/node_modules/tapable/lib/Tapab
le.js:60:69)
    at Compilation.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/Compilation
.js:563:8)
    at Compilation.applyPluginsAsync (/Users/z/Projects/Douban/share/design/assets/node_modules/tapable/lib/Tapab
le.js:60:69)
    at Compilation.seal (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/Compilation.js:525
:7)
    at Compiler.<anonymous> (/Users/z/Projects/Douban/share/design/assets/node_modules/webpack/lib/Compiler.js:39
7:15)

````

packages.json:

```
{
  "name": "assets",
  "private": true,
  "version": "1.0.0",
  "moduleRoots": [
    "./src"
  ],
  "main": "src/design/index.jsx",
  "dependencies": {
    "axios": "^0.16.1",
    "babel-runtime": "^6.3.19",
    "bootstrap": "^3.3.7",
    "bootstrap-loader": "^2.0.0",
    "bplist-parser": "^0.1.1",
    "classnames": "^2.2.1",
    "clipboard-js": "^0.3.3",
    "core-decorators": "^0.19.0",
    "debug": "^2.6.7",
    "es6-promise": "^4.1.0",
    "exports-loader": "^0.6.3",
    "form-serialize": "^0.7.0",
    "immuter": "^1.0.3",
    "iscroll": "^5.2.0",
    "ismobilejs": "^0.4.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.2.1",
    "jszip": "^3.1.3",
    "keymirror": "^0.1.1",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.3.4",
    "lodash.truncate": "^4.4.2",
    "lru-cache": "^4.0.2",
    "material-design-icons": "^3.0.1",
    "object-path": "^0.11.4",
    "rc-tooltip": "^3.4.3",
    "react": "^15.4.1",
    "react-addons-create-fragment": "^15.4.1",
    "react-addons-css-transition-group": "^15.5.2",
    "react-addons-transition-group": "^15.5.2",
    "react-bootstrap": "^0.31.0",
    "react-dnd": "^2.0.2",
    "react-dnd-html5-backend": "^2.0.0",
    "react-dom": "^15.4.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-icons": "^2.2.5",
    "react-image-lightbox": "^4.0.0",
    "react-loading": "^0.1.2",
    "react-mixin": "^3.0.3",
    "react-motion": "^0.4.6",
    "react-paginate": "^2.0.1",
    "react-rater": "^0.3.5",
    "react-redux": "^4.0.0",
    "react-router": "^3.0.0",
    "react-syntax-highlight": "^0.0.6",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.0.4",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-logger": "^2.1.1",
    "redux-promise-middleware": "^4.3.0",
    "redux-thunk": "^2.1.0",
    "rupture": "^0.6.2",
    "sketch-constants": "^1.0.2",
    "superagent": "^3.1.0",
    "wheel": "^0.0.5"
  },
  "devDependencies": {
    "ansi-to-html-umd": "~0.4.2",
    "autoprefixer": "^6.5.3",
    "babel-core": "^6.2.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-do-expressions": "^6.8.0",
    "babel-plugin-transform-runtime": "^6.4.3",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-0": "^6.1.18",
    "body-parser": "^1.15.2",
    "css-loader": "~0.26.0",
    "eslint": "^3.11.1",
    "eslint-import-resolver-babel-module": "^3.0.0",
    "eslint-loader": "^1.2.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^6.7.1",
    "express": "~4.14.0",
    "fast-uglifyjs-plugin": "^0.1.7",
    "file-loader": "^0.9.0",
    "http-proxy-middleware": "^0.17.2",
    "postcss-loader": "^1.1.1",
    "postcss-smart-import": "^0.6.0",
    "precss": "^1.4.0",
    "pug": "^2.0.0-beta6",
    "redux-devtools": "^3.3.1",
    "redux-devtools-diff-monitor": "^5.0.5",
    "style-loader": "^0.13.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.4.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.9",
    "webpack-dev-middleware": "^1.5.1",
    "webpack-dev-server": "^1.16.2",
    "webpack-hot-middleware": "^2.6.4"
  }
}

```

**Comment by keller35** [comment]
@skyblue @zaaack 
我已经修复 sourcemap 相关的bug，npm更新包到0.2.0版本即可正常使用。
不好意思这么久才修复，如果还有问题欢迎重新打开或者提新的issue。
